#!/bin/bash
# -------- Terminal settings ---------------------------------------------------
PS_USER_MACHINE="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]"
COLOR_WORKING_DIR="\033[95;38;5;214m"
export PS1="${PS_USER_MACHINE}\h:\[$COLOR_WORKING_DIR\]\w\[\033[m\]\$ "
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad

function set_simple_ps1 {
    # export PS1="\u@\h [\t]> " 
    export PS1="${PS_USER_MACHINE}\h:\[$COLOR_WORKING_DIR\]\W\[\033[m\]\$ "
}

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# ------------ DART -----------------------------------------------------------
export BUILD_WITH_DART=1

# ------------ Aliases --------------------------------------------------------
# alias ls='ls -GFh'
alias open="evince"
alias e="emacs -nw"
alias ll="ls -la"
CATKIN_WS=${HOME}/Dropbox/catkin_ws_research/workspace/
alias cdrieef="cd ${CATKIN_WS}src/catkin/ioc/rieef-uw/"
alias cdweb="cd ${HOME}/Dropbox/documents_perso/Website/humans-robots-motion"
alias cdmath="cd ${HOME}/Documents/mlr_documents/teaching/17-Math"
alias cdbashscripts="cd ${HOME}/bash_scripts"

# -------------- Printers (U. Stuttgart)---------------------------------------
export CUPS_USER=mainprjm

# ------------ Start SSH Agent ------------------------------------------------
if [ ! -S ~/.ssh/ssh_auth_sock ]; then
  eval `ssh-agent`
  ln -sf "$SSH_AUTH_SOCK" ~/.ssh/ssh_auth_sock
fi
export SSH_AUTH_SOCK=~/.ssh/ssh_auth_sock
ssh-add -l | grep "The agent has no identities" && ssh-add

# -------------- Path --------------------------------------------------------
export PATH="~/bash_scripts:${PATH}"

# ------------ ROS -----------------------------------------------------------
source /opt/ros/melodic/setup.bash
