#!/bin/bash
# -------- Terminal settings --------------------------------------------------
PS_USER_MACHINE="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]"
export PS1="${PS_USER_MACHINE}\h:\[\033[33;1m\]\w\[\033[m\]\$ "
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad

function set_simple_ps1 {
    # export PS1="\u@\h [\t]> " 
    export PS1="${PS_USER_MACHINE}\h:\[\033[33;1m\]\W\[\033[m\]\$ "
}
# ------------ Aliases --------------------------------------------------------
# alias ls='ls -GFh'
alias e="emacs -nw"
alias ll="ls -la"
alias text="open /Applications/TextEdit.app"
CATKIN_WS=${HOME}/Dropbox/catkin_ws_research/workspace/
alias cdrieef="cd ${CATKIN_WS}src/catkin/ioc/rieef-uw/"
alias cdweb="cd ${HOME}/Dropbox/documents_perso/Website/humans-robots-motion"
alias cdmath="cd ${HOME}/Documents/mlr_documents/teaching/17-Math"
alias cdbashscripts="cd ${HOME}/bash_scripts"

# ------------ Start SSH Agent ------------------------------------------------
if [ ! -S ~/.ssh/ssh_auth_sock ]; then
  eval `ssh-agent`
  ln -sf "$SSH_AUTH_SOCK" ~/.ssh/ssh_auth_sock
fi
export SSH_AUTH_SOCK=~/.ssh/ssh_auth_sock
ssh-add -l | grep "The agent has no identities" && ssh-add

# -------------- Path ---------------------------------------------------------
export PATH="/Applications/Firefox.app/Contents/MacOS:${PATH}"
export PATH="~/bash_scripts:${PATH}"

# -------------- Printers -----------------------------------------------------
export CUPS_USER=mainprjm

#------------- Move3D ---------------------------------------------------------
# This is added automatically when installed.
MOVE3D_LAUNCH_DIR=${HOME}/workspace/move3d/move3d-launch
export MOVE3D_INSTALL_DIR=${MOVE3D_LAUNCH_DIR}/../install
export HOME_MOVE3D=${MOVE3D_LAUNCH_DIR}/../libmove3d
export PKG_CONFIG_PATH=${MOVE3D_LAUNCH_DIR}/../install/lib/pkgconfig:$PKG_CONFIG_PATH
export PATH=${MOVE3D_LAUNCH_DIR}/../install/bin:$PATH
export DYLD_LIBRARY_PATH=${MOVE3D_LAUNCH_DIR}/../install/lib:$DYLD_LIBRARY_PATH

#------------- Pinocchio ------------------------------------------------------
export PATH=/usr/local/bin:$PATH
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH
export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
# export PYTHONPATH=/usr/local/lib/python2.7/site-packages:$PYTHONPATH

#------------- Conda ----------------------------------------------------------

export PATH=~/anaconda2/bin:$PATH
# source activate conda-env
# source activate env-pytorch

# TEST PYRIEEF
# conda create --name env-pyrieef
# source activate env-pyrieef
# source deactivate env-pyrieef
# conda remove -n env-pyrieef --all

# python2 enviornment
function ws_pyrieef2 {
    # conda create -n env-pyrieef-py2 python=2.7 anaconda
    source activate env-pyrieef-py2
    # source deactivate env-pyrieef-py3
    # conda remove -n env-pyrieef-py3 --all
}

# python3 enviornment
function ws_pyrieef3 {
    # conda create -n env-pyrieef-py3 python=3.6 anaconda
    source activate env-pyrieef-py3
    # source deactivate env-pyrieef-py3
    # conda remove -n env-pyrieef-py3 --all
}

# python2 enviornment
function ws_pyrieef36 {
    # conda create -n env-pyrieef-py36 python=3.6 anaconda
    source activate env-pyrieef-py36
    # source deactivate env-pyrieef-py36
    # conda remove -n env-pyrieef-py36 --all
}

function ws_learch3 {
    # conda create -n env-learch-py3 python=3.6 anaconda
    source activate env-learch-py3
    # source deactivate env-learch-py3
    # conda remove -n env-learch-py3 --all
    export PYTHONPATH=${HOME}/workspace/pedestrian-trajectories:${PYTHONPATH}
}

# conda create -n env-pyrieef-py3.5 python=3.5 anaconda
# source activate env-pyrieef-py3.5
